-- STORED PROCEDURE
USE db_name;
DELIMITER $$
CREATE PROCEDURE test()
BEGIN
	
END $$
DELIMITER ;

-- STORED FUNCTION
USE db_name;
DELIMITER $$
CREATE FUNCTION Funcao(var int)
RETURNS INT READS SQL DATA
BEGIN
	DECLARE var INT;
    RETURN var;
END $$
DELIMITER ;

-- TRIGGER
USE db_name;
DELIMITER $$
CREATE TRIGGER trigger_name
	-- [BEFORE | AFTER] [INSERT | UPDATE | DELETE] ON tabela
	FOR EACH ROW
BEGIN
    -- SET NEW.campo_tabela = valor,
END $$
DELIMITER $$ ;
